import type { Metadata } from "next";
import { Kumbh_Sans, Roboto_Slab, Space_Mono } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "./redux/provider";

const Kumbh = Kumbh_Sans({ subsets: ["latin"], weight: ["400", "700"] });
const Roboto = Roboto_Slab({ subsets: ["latin"], weight: ["400", "700"] });
const SpaceMono = Space_Mono({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "pomodoro app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={(Kumbh.className, Roboto.className, SpaceMono.className)}
      >
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
